//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_MiniProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookTbl
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Tag { get; set; }
        public string Image { get; set; }
        public int Year_of_publishing { get; set; }
    }
}
